//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace TUSZ.PhoneClient.RoutePlannerService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VM_Stop", Namespace="http://schemas.datacontract.org/2004/07/TUSZ.Common.ViewModels")]
    public partial class VM_Stop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private float latField;
        
        private float lngField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float lat {
            get {
                return this.latField;
            }
            set {
                if ((this.latField.Equals(value) != true)) {
                    this.latField = value;
                    this.RaisePropertyChanged("lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float lng {
            get {
                return this.lngField;
            }
            set {
                if ((this.lngField.Equals(value) != true)) {
                    this.lngField = value;
                    this.RaisePropertyChanged("lng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VM_PlanResult", Namespace="http://schemas.datacontract.org/2004/07/TUSZ.Common.ViewModels")]
    public partial class VM_PlanResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string failMessageField;
        
        private bool isFailedField;
        
        private TUSZ.PhoneClient.RoutePlannerService.VM_Plan planField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string failMessage {
            get {
                return this.failMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.failMessageField, value) != true)) {
                    this.failMessageField = value;
                    this.RaisePropertyChanged("failMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isFailed {
            get {
                return this.isFailedField;
            }
            set {
                if ((this.isFailedField.Equals(value) != true)) {
                    this.isFailedField = value;
                    this.RaisePropertyChanged("isFailed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TUSZ.PhoneClient.RoutePlannerService.VM_Plan plan {
            get {
                return this.planField;
            }
            set {
                if ((object.ReferenceEquals(this.planField, value) != true)) {
                    this.planField = value;
                    this.RaisePropertyChanged("plan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VM_Plan", Namespace="http://schemas.datacontract.org/2004/07/TUSZ.Common.ViewModels")]
    public partial class VM_Plan : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string algorythm_nameField;
        
        private TUSZ.PhoneClient.RoutePlannerService.VM_Stop destinationField;
        
        private System.DateTime plan_beginsField;
        
        private System.DateTime plan_endsField;
        
        private System.TimeSpan plan_timeField;
        
        private TUSZ.PhoneClient.RoutePlannerService.VM_Stop sourceField;
        
        private System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_TravelGroup> travel_groupsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string algorythm_name {
            get {
                return this.algorythm_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.algorythm_nameField, value) != true)) {
                    this.algorythm_nameField = value;
                    this.RaisePropertyChanged("algorythm_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TUSZ.PhoneClient.RoutePlannerService.VM_Stop destination {
            get {
                return this.destinationField;
            }
            set {
                if ((object.ReferenceEquals(this.destinationField, value) != true)) {
                    this.destinationField = value;
                    this.RaisePropertyChanged("destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime plan_begins {
            get {
                return this.plan_beginsField;
            }
            set {
                if ((this.plan_beginsField.Equals(value) != true)) {
                    this.plan_beginsField = value;
                    this.RaisePropertyChanged("plan_begins");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime plan_ends {
            get {
                return this.plan_endsField;
            }
            set {
                if ((this.plan_endsField.Equals(value) != true)) {
                    this.plan_endsField = value;
                    this.RaisePropertyChanged("plan_ends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan plan_time {
            get {
                return this.plan_timeField;
            }
            set {
                if ((this.plan_timeField.Equals(value) != true)) {
                    this.plan_timeField = value;
                    this.RaisePropertyChanged("plan_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TUSZ.PhoneClient.RoutePlannerService.VM_Stop source {
            get {
                return this.sourceField;
            }
            set {
                if ((object.ReferenceEquals(this.sourceField, value) != true)) {
                    this.sourceField = value;
                    this.RaisePropertyChanged("source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_TravelGroup> travel_groups {
            get {
                return this.travel_groupsField;
            }
            set {
                if ((object.ReferenceEquals(this.travel_groupsField, value) != true)) {
                    this.travel_groupsField = value;
                    this.RaisePropertyChanged("travel_groups");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VM_TravelGroup", Namespace="http://schemas.datacontract.org/2004/07/TUSZ.Common.ViewModels")]
    public partial class VM_TravelGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TUSZ.PhoneClient.RoutePlannerService.VM_Stop fromField;
        
        private System.DateTime from_timeField;
        
        private System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_PassedStop> passed_stopsField;
        
        private TUSZ.PhoneClient.RoutePlannerService.VM_Route routeField;
        
        private TUSZ.PhoneClient.RoutePlannerService.VM_Stop toField;
        
        private System.DateTime to_timeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TUSZ.PhoneClient.RoutePlannerService.VM_Stop from {
            get {
                return this.fromField;
            }
            set {
                if ((object.ReferenceEquals(this.fromField, value) != true)) {
                    this.fromField = value;
                    this.RaisePropertyChanged("from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime from_time {
            get {
                return this.from_timeField;
            }
            set {
                if ((this.from_timeField.Equals(value) != true)) {
                    this.from_timeField = value;
                    this.RaisePropertyChanged("from_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_PassedStop> passed_stops {
            get {
                return this.passed_stopsField;
            }
            set {
                if ((object.ReferenceEquals(this.passed_stopsField, value) != true)) {
                    this.passed_stopsField = value;
                    this.RaisePropertyChanged("passed_stops");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TUSZ.PhoneClient.RoutePlannerService.VM_Route route {
            get {
                return this.routeField;
            }
            set {
                if ((object.ReferenceEquals(this.routeField, value) != true)) {
                    this.routeField = value;
                    this.RaisePropertyChanged("route");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TUSZ.PhoneClient.RoutePlannerService.VM_Stop to {
            get {
                return this.toField;
            }
            set {
                if ((object.ReferenceEquals(this.toField, value) != true)) {
                    this.toField = value;
                    this.RaisePropertyChanged("to");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime to_time {
            get {
                return this.to_timeField;
            }
            set {
                if ((this.to_timeField.Equals(value) != true)) {
                    this.to_timeField = value;
                    this.RaisePropertyChanged("to_time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VM_Route", Namespace="http://schemas.datacontract.org/2004/07/TUSZ.Common.ViewModels")]
    public partial class VM_Route : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string html_base_colorField;
        
        private string html_text_colorField;
        
        private int idField;
        
        private string nameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string html_base_color {
            get {
                return this.html_base_colorField;
            }
            set {
                if ((object.ReferenceEquals(this.html_base_colorField, value) != true)) {
                    this.html_base_colorField = value;
                    this.RaisePropertyChanged("html_base_color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string html_text_color {
            get {
                return this.html_text_colorField;
            }
            set {
                if ((object.ReferenceEquals(this.html_text_colorField, value) != true)) {
                    this.html_text_colorField = value;
                    this.RaisePropertyChanged("html_text_color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VM_PassedStop", Namespace="http://schemas.datacontract.org/2004/07/TUSZ.Common.ViewModels")]
    public partial class VM_PassedStop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool getOnOffField;
        
        private TUSZ.PhoneClient.RoutePlannerService.VM_Stop stopField;
        
        private System.DateTime whenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool getOnOff {
            get {
                return this.getOnOffField;
            }
            set {
                if ((this.getOnOffField.Equals(value) != true)) {
                    this.getOnOffField = value;
                    this.RaisePropertyChanged("getOnOff");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TUSZ.PhoneClient.RoutePlannerService.VM_Stop stop {
            get {
                return this.stopField;
            }
            set {
                if ((object.ReferenceEquals(this.stopField, value) != true)) {
                    this.stopField = value;
                    this.RaisePropertyChanged("stop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime when {
            get {
                return this.whenField;
            }
            set {
                if ((this.whenField.Equals(value) != true)) {
                    this.whenField = value;
                    this.RaisePropertyChanged("when");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoutePlannerService.IRoutePlannerService")]
    public interface IRoutePlannerService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IRoutePlannerService/GetStops", ReplyAction="http://tempuri.org/IRoutePlannerService/GetStopsResponse")]
        System.IAsyncResult BeginGetStops(string name, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_Stop> EndGetStops(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IRoutePlannerService/Plan", ReplyAction="http://tempuri.org/IRoutePlannerService/PlanResponse")]
        System.IAsyncResult BeginPlan(int fromStopIdx, int toStopIdx, System.AsyncCallback callback, object asyncState);
        
        TUSZ.PhoneClient.RoutePlannerService.VM_PlanResult EndPlan(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoutePlannerServiceChannel : TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStopsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStopsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_Stop> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_Stop>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public PlanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public TUSZ.PhoneClient.RoutePlannerService.VM_PlanResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((TUSZ.PhoneClient.RoutePlannerService.VM_PlanResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoutePlannerServiceClient : System.ServiceModel.ClientBase<TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService>, TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService {
        
        private BeginOperationDelegate onBeginGetStopsDelegate;
        
        private EndOperationDelegate onEndGetStopsDelegate;
        
        private System.Threading.SendOrPostCallback onGetStopsCompletedDelegate;
        
        private BeginOperationDelegate onBeginPlanDelegate;
        
        private EndOperationDelegate onEndPlanDelegate;
        
        private System.Threading.SendOrPostCallback onPlanCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public RoutePlannerServiceClient() {
        }
        
        public RoutePlannerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutePlannerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutePlannerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutePlannerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetStopsCompletedEventArgs> GetStopsCompleted;
        
        public event System.EventHandler<PlanCompletedEventArgs> PlanCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService.BeginGetStops(string name, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStops(name, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_Stop> TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService.EndGetStops(System.IAsyncResult result) {
            return base.Channel.EndGetStops(result);
        }
        
        private System.IAsyncResult OnBeginGetStops(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            return ((TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService)(this)).BeginGetStops(name, callback, asyncState);
        }
        
        private object[] OnEndGetStops(System.IAsyncResult result) {
            System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_Stop> retVal = ((TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService)(this)).EndGetStops(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStopsCompleted(object state) {
            if ((this.GetStopsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStopsCompleted(this, new GetStopsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStopsAsync(string name) {
            this.GetStopsAsync(name, null);
        }
        
        public void GetStopsAsync(string name, object userState) {
            if ((this.onBeginGetStopsDelegate == null)) {
                this.onBeginGetStopsDelegate = new BeginOperationDelegate(this.OnBeginGetStops);
            }
            if ((this.onEndGetStopsDelegate == null)) {
                this.onEndGetStopsDelegate = new EndOperationDelegate(this.OnEndGetStops);
            }
            if ((this.onGetStopsCompletedDelegate == null)) {
                this.onGetStopsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStopsCompleted);
            }
            base.InvokeAsync(this.onBeginGetStopsDelegate, new object[] {
                        name}, this.onEndGetStopsDelegate, this.onGetStopsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService.BeginPlan(int fromStopIdx, int toStopIdx, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPlan(fromStopIdx, toStopIdx, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TUSZ.PhoneClient.RoutePlannerService.VM_PlanResult TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService.EndPlan(System.IAsyncResult result) {
            return base.Channel.EndPlan(result);
        }
        
        private System.IAsyncResult OnBeginPlan(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int fromStopIdx = ((int)(inValues[0]));
            int toStopIdx = ((int)(inValues[1]));
            return ((TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService)(this)).BeginPlan(fromStopIdx, toStopIdx, callback, asyncState);
        }
        
        private object[] OnEndPlan(System.IAsyncResult result) {
            TUSZ.PhoneClient.RoutePlannerService.VM_PlanResult retVal = ((TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService)(this)).EndPlan(result);
            return new object[] {
                    retVal};
        }
        
        private void OnPlanCompleted(object state) {
            if ((this.PlanCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PlanCompleted(this, new PlanCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PlanAsync(int fromStopIdx, int toStopIdx) {
            this.PlanAsync(fromStopIdx, toStopIdx, null);
        }
        
        public void PlanAsync(int fromStopIdx, int toStopIdx, object userState) {
            if ((this.onBeginPlanDelegate == null)) {
                this.onBeginPlanDelegate = new BeginOperationDelegate(this.OnBeginPlan);
            }
            if ((this.onEndPlanDelegate == null)) {
                this.onEndPlanDelegate = new EndOperationDelegate(this.OnEndPlan);
            }
            if ((this.onPlanCompletedDelegate == null)) {
                this.onPlanCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPlanCompleted);
            }
            base.InvokeAsync(this.onBeginPlanDelegate, new object[] {
                        fromStopIdx,
                        toStopIdx}, this.onEndPlanDelegate, this.onPlanCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService CreateChannel() {
            return new RoutePlannerServiceClientChannel(this);
        }
        
        private class RoutePlannerServiceClientChannel : ChannelBase<TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService>, TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService {
            
            public RoutePlannerServiceClientChannel(System.ServiceModel.ClientBase<TUSZ.PhoneClient.RoutePlannerService.IRoutePlannerService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetStops(string name, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = name;
                System.IAsyncResult _result = base.BeginInvoke("GetStops", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_Stop> EndGetStops(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_Stop> _result = ((System.Collections.Generic.List<TUSZ.PhoneClient.RoutePlannerService.VM_Stop>)(base.EndInvoke("GetStops", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPlan(int fromStopIdx, int toStopIdx, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = fromStopIdx;
                _args[1] = toStopIdx;
                System.IAsyncResult _result = base.BeginInvoke("Plan", _args, callback, asyncState);
                return _result;
            }
            
            public TUSZ.PhoneClient.RoutePlannerService.VM_PlanResult EndPlan(System.IAsyncResult result) {
                object[] _args = new object[0];
                TUSZ.PhoneClient.RoutePlannerService.VM_PlanResult _result = ((TUSZ.PhoneClient.RoutePlannerService.VM_PlanResult)(base.EndInvoke("Plan", _args, result)));
                return _result;
            }
        }
    }
}
